version: 2
jobs:
  backend_tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend/
            pip install -r requirements-dev.txt --user
            pip install -r requirements.txt --user
            wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
            echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org
            pytest tests
  backend_format:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check --exclude venv\*
  frontend_format:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install --no-optional
            npm run format:check
workflows:
  version: 2
  build-test:
    jobs:
      - frontend_format
      - backend_format
      - backend_tests
