version: 2
jobs:
  backend_format:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check 
  frontend_format:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install --no-optional
            npm run format:check
workflows:
  version: 2
  build-test:
    jobs:
      - frontend_format
      - backend_format
