version: 2
jobs:
  backend_tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend/
            pip install -r requirements-dev.txt --user
            pip install -r requirements.txt --user
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
            echo "deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org
            sudo service mongod restart
            ls /usr/bin
            echo aldfjalkdjflkajdflksjalkfjsdlfjalfjlasjdfklajfdljalfdjlajfdljsklfjas
            ls /usr/local/bin
            pytest tests
  backend_format:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: |
            cd backend
            pip install -r requirements-dev.txt --user
            /home/circleci/.local/bin/black . --check --exclude venv\*
  frontend_format:
    docker:
      - image: node:10.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm install --no-optional
            npm run format:check
workflows:
  version: 2
  build-test:
    jobs:
      - frontend_format
      - backend_format
      - backend_tests
